name: cyclotron
version: '${project.version}'
main: com.github.aruka.cyclotron.Cyclotron
api-version: '1.20'
authors: [Aruka]
description: "\"cyclotron\" is a simple auto crafter what runs on chests."
commands:
  cyclotron:
    description: "(Un)Register and see recipes command."
    usage: "'/cyclotron <register | unregister> <Result Item ID>' or '/filter info'"
    permission: cyclotron.default

permissions:
  cyclotron.default:
    default: true

  cyclotron.clear:
    default: op